### ISSUE TITLE
Search doesnt allow double faced cards

### ISSUE THREAD

**Issue by brianwchou** [brianwchou/deck-builder-web#5]
The software currently doesn't handle double faced cards.

The data for the double face card data is different from normal cards. We need to first see how the double faced JSON is defined and find a way to generalize cards.

**Comment by zhc1289** [comment]
Currently, we filter out cards and only accept the card if its layout value is "normal".  Double faced cards have the layout value "transform".  Another difference is that double faced cards have the property "card_faces".  This property contains an array of size 2.  Each array contains information of one side of the card.

**Comment by brianwchou** [comment]
Okay, I didn't understand what meld was and didn't know that they exist. But I see now that they are 2 cards that make 1 card. [example here](https://mtg.gamepedia.com/Meld#Cards_with_meld)

Let's focus on transform at the moment. There aren't that many meld cards and I've never seen anyone play with them.
